python new_run.py \
    --output_dir=./saved_models \
    --tokenizer_name=D:\\CodeLibrary\\CodeBERT\\codebert-base \
    --model_name_or_path=D:\\CodeLibrary\\CodeBERT\\codebert-base \
    --do_train \
    --train_data_file=D:\\CodeLibrary\\CodeBERT\\dataset\\train.jsonl \
    --eval_data_file=D:\\CodeLibrary\\CodeBERT\\dataset\\valid.jsonl \
    --num_train_epochs 8 \
    --block_size 256 \
    --train_batch_size 8 \
    --eval_batch_size 16 \
    --learning_rate 2e-5 \
    --max_grad_norm 1.0 \
    --seed 123456  2>&1 | tee train_c_cpp_replaced.log